### ISSUE TITLE
Ubuntu Kernel Installation fails

### ISSUE THREAD

**Issue by Honest-Objections** [raphael/linux-samus#184]
Running `sudo dpkg -i *.deb` results in `Error! Bad return status for module build on kernel: 4.9.6-ph+ (x86_64)`

`/var/lib/dkms/ndiswrapper/1.59/build/wrapndis.c: In function ‘tx_worker’:
/var/lib/dkms/ndiswrapper/1.59/build/wrapndis.c:707:16: error: ‘struct net_device’ has no member named ‘trans_start’
    wnd->net_dev->trans_start = jiffies;
                ^
scripts/Makefile.build:293: recipe for target '/var/lib/dkms/ndiswrapper/1.59/build/wrapndis.o' failed
make[1]: *** [/var/lib/dkms/ndiswrapper/1.59/build/wrapndis.o] Error 1
Makefile:1490: recipe for target '_module_/var/lib/dkms/ndiswrapper/1.59/build' failed
make: *** [_module_/var/lib/dkms/ndiswrapper/1.59/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.9.6-ph+'`

**Comment by nskaggs** [comment]
@Honest-Objections which version of ubuntu? Also, a more complete log would help.

**Comment by blocksonic** [comment]
same problem. Linux Mint 18.1 

G50 kernel # sudo dpkg -i linux-headers-4.9.0*.deb linux-image-4.9.0*.deb(Reading database ... 597307 files and directories currently installed.)
Preparing to unpack linux-headers-4.9.0-040900_4.9.0-040900.201612111631_all.deb ...
Unpacking linux-headers-4.9.0-040900 (4.9.0-040900.201612111631) over (4.9.0-040900.201612111631) ...
Preparing to unpack linux-headers-4.9.0-040900-generic_4.9.0-040900.201612111631_amd64.deb ...
Unpacking linux-headers-4.9.0-040900-generic (4.9.0-040900.201612111631) over (4.9.0-040900.201612111631) ...
Preparing to unpack linux-image-4.9.0-040900-generic_4.9.0-040900.201612111631_amd64.deb ...
Done.
Unpacking linux-image-4.9.0-040900-generic (4.9.0-040900.201612111631) ...
dpkg-deb (subprocess): cannot copy archive member from 'linux-image-4.9.0-040900-generic_4.9.0-040900.201612111631_amd64.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb (subprocess): decompressing archive member: internal bzip2 read error: 'UNEXPECTED_EOF'
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg: error processing archive linux-image-4.9.0-040900-generic_4.9.0-040900.201612111631_amd64.deb (--install):
 cannot copy extracted data for './boot/vmlinuz-4.9.0-040900-generic' to '/boot/vmlinuz-4.9.0-040900-generic.dpkg-new': unexpected end of file or stream
Examining /etc/kernel/postrm.d .
run-parts: executing /etc/kernel/postrm.d/initramfs-tools 4.9.0-040900-generic /boot/vmlinuz-4.9.0-040900-generic
run-parts: executing /etc/kernel/postrm.d/zz-update-grub 4.9.0-040900-generic /boot/vmlinuz-4.9.0-040900-generic
Setting up linux-headers-4.9.0-040900 (4.9.0-040900.201612111631) ...
Setting up linux-headers-4.9.0-040900-generic (4.9.0-040900.201612111631) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.9.0-040900-generic /boot/vmlinuz-4.9.0-040900-generic
Error! Bad return status for module build on kernel: 4.9.0-040900-generic (x86_64)
Consult /var/lib/dkms/ndiswrapper/1.59/build/make.log for more information.
Errors were encountered while processing:
 linux-image-4.9.0-040900-generic_4.9.0-040900.201612111631_amd64.deb

------------- make.log file ----------------------->
DKMS make.log for ndiswrapper-1.59 for kernel 4.9.0-040900-generic (x86_64)
Tue Feb 21 17:06:36 BRT 2017
make: Entering directory '/usr/src/linux-headers-4.9.0-040900-generic'
  LD      /var/lib/dkms/ndiswrapper/1.59/build/built-in.o
  MKEXPORT /var/lib/dkms/ndiswrapper/1.59/build/crt_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.59/build/hal_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.59/build/ndis_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.59/build/ntoskernel_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.59/build/ntoskernel_io_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.59/build/rtl_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.59/build/usb_exports.h
  MKSTUBS /var/lib/dkms/ndiswrapper/1.59/build/win2lin_stubs.h
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/crt.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/hal.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/iw_ndis.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/loader.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/ndis.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/ntoskernel.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/ntoskernel_io.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/pe_linker.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/pnp.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/proc.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/rtl.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/wrapmem.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/wrapndis.o
/var/lib/dkms/ndiswrapper/1.59/build/wrapndis.c: In function ‘tx_worker’:
/var/lib/dkms/ndiswrapper/1.59/build/wrapndis.c:707:16: error: ‘struct net_device’ has no member named ‘trans_start’
    wnd->net_dev->trans_start = jiffies;
                ^
scripts/Makefile.build:293: recipe for target '/var/lib/dkms/ndiswrapper/1.59/build/wrapndis.o' failed
make[1]: *** [/var/lib/dkms/ndiswrapper/1.59/build/wrapndis.o] Error 1
Makefile:1496: recipe for target '_module_/var/lib/dkms/ndiswrapper/1.59/build' failed
make: *** [_module_/var/lib/dkms/ndiswrapper/1.59/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.9.0-040900-generic'

**Comment by Honest-Objections** [comment]
My issue was also on Linux Mint 18.1, worth noting the kernel still installed

**Comment by blocksonic** [comment]
For me it did not. Never got the the point of updating Grub. Kernel 4.10 also had errors but did get to seemed to finish. Have not rebooted yet...

brad@G50 ~/working/kernel/kern410 $ sudo dpkg -i *.deb
Selecting previously unselected package linux-headers-4.10.0-041000.
(Reading database ... 597307 files and directories currently installed.)
Preparing to unpack linux-headers-4.10.0-041000_4.10.0-041000.201702191831_all.deb ...
Unpacking linux-headers-4.10.0-041000 (4.10.0-041000.201702191831) ...
Selecting previously unselected package linux-headers-4.10.0-041000-generic.
Preparing to unpack linux-headers-4.10.0-041000-generic_4.10.0-041000.201702191831_amd64.deb ...
Unpacking linux-headers-4.10.0-041000-generic (4.10.0-041000.201702191831) ...
Selecting previously unselected package linux-image-4.10.0-041000-generic.
Preparing to unpack linux-image-4.10.0-041000-generic_4.10.0-041000.201702191831_amd64.deb ...
Done.
Unpacking linux-image-4.10.0-041000-generic (4.10.0-041000.201702191831) ...
Setting up linux-headers-4.10.0-041000 (4.10.0-041000.201702191831) ...
Setting up linux-headers-4.10.0-041000-generic (4.10.0-041000.201702191831) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.10.0-041000-generic /boot/vmlinuz-4.10.0-041000-generic
Error! Bad return status for module build on kernel: 4.10.0-041000-generic (x86_64)
Consult /var/lib/dkms/ndiswrapper/1.59/build/make.log for more information.
Error! Bad return status for module build on kernel: 4.10.0-041000-generic (x86_64)
Consult /var/lib/dkms/virtualbox-guest/5.0.32/build/make.log for more information.
Setting up linux-image-4.10.0-041000-generic (4.10.0-041000.201702191831) ...
Running depmod.
update-initramfs: deferring update (hook will be called later)
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 4.10.0-041000-generic /boot/vmlinuz-4.10.0-041000-generic
run-parts: executing /etc/kernel/postinst.d/dkms 4.10.0-041000-generic /boot/vmlinuz-4.10.0-041000-generic
Error! Bad return status for module build on kernel: 4.10.0-041000-generic (x86_64)
Consult /var/lib/dkms/ndiswrapper/1.59/build/make.log for more information.
Error! Bad return status for module build on kernel: 4.10.0-041000-generic (x86_64)
Consult /var/lib/dkms/virtualbox-guest/5.0.32/build/make.log for more information.
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 4.10.0-041000-generic /boot/vmlinuz-4.10.0-041000-generic
update-initramfs: Generating /boot/initrd.img-4.10.0-041000-generic
W: Possible missing firmware /lib/firmware/radeon/si58_mc.bin for module radeon
W: Possible missing firmware /lib/firmware/radeon/banks_k_2_smc.bin for module radeon
W: Possible missing firmware /lib/firmware/radeon/si58_mc.bin for module amdgpu
W: Possible missing firmware /lib/firmware/radeon/banks_k_2_smc.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/polaris12_smc.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/tonga_k_smc.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/topaz_k_smc.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/polaris12_mc.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/polaris12_rlc.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/polaris12_mec2.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/polaris12_mec.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/polaris12_me.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/polaris12_pfp.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/polaris12_ce.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/polaris12_sdma1.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/polaris12_sdma.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/polaris12_uvd.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/polaris12_vce.bin for module amdgpu
run-parts: executing /etc/kernel/postinst.d/pm-utils 4.10.0-041000-generic /boot/vmlinuz-4.10.0-041000-generic
run-parts: executing /etc/kernel/postinst.d/unattended-upgrades 4.10.0-041000-generic /boot/vmlinuz-4.10.0-041000-generic
run-parts: executing /etc/kernel/postinst.d/zz-update-grub 4.10.0-041000-generic /boot/vmlinuz-4.10.0-041000-generic
Generating grub configuration file ...
...
Adding boot menu entry for EFI firmware configuration
done
